Домашнее задание к 1 уроку (first homework)
nikodim-an/geekshop pull request #1
Opened 2021-06-26 08:58 UTC by nikodim-an

2021-06-27 15:46 UTC, Vokler requested changes

2021-06-27 15:46 UTC, Vokler commented on geekshop/settings.py
> +    BASE_DIR / 'static',
Если используете список, запятая не нужна

2021-06-27 15:46 UTC, Vokler commented
В остальном все отлично, только это маленькое замечание

2021-06-28 08:57 UTC, nikodim-an commented on geekshop/settings.py
> +    BASE_DIR / 'static',
Что-то я затупил. Хотел кортеж использовать - они пошустрее работают и видимо подумал об одном, а сделал другое. Тогда непонятно почему контроль синтаксиса пропустил? Хотя возможно я чего-то не правильно помню. А что мне теперь делать-то я ж не сдавал ни разу и пуреквестом не пользовался - тупо храню репозиторий с версиями на сервере...

2021-06-28 11:35 UTC, Vokler commented on geekshop/settings.py
> +    BASE_DIR / 'static',
Вы правильно внесли изменения, все ок. Я вижу и сейчас смержу.

2021-06-28 11:35 UTC, Vokler approved these changes

2021-06-28 11:35 UTC, merged